### PR TITLE
issue/3851-cmcd-tb

### LINKED ISSUE #3851: CMCD top bitrate (tb) is being reported incorrectly
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Safari, Chrome, Firefox, Edge

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

```
{
   cmcd: {
    enabled: true
  }
}
```

**What did you do?**

1. Start playback of any stream
2. View the network requests for any video or audio segments and inspect the CMCD query string 

**What did you expect to happen?**
- The `tb` (top bitrate) property should honor bitrate/size ABR constraints and only report the top _playable_ bitrate. 
- The `tb` property should also only report the bandwidth for that segments type (audio, video, muxed).

**What actually happened?**
- The `tb` property is the same for all requests, and it's locked to the bandwidth of the highest variant in the manifest.
- The `tb` property is the same regardless of the segment type.

### PR DESCRIPTION
**Pull request by littlespex**
## Description
Fix incorrect top bitrate CMCD reporting by:
- Honoring the player's current bitrate/size ABR constraints.
- Only reporting the bandwidth for that segments type (audio, video, muxed).

Fixes #3851

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] I have signed the Google CLA <https://cla.developers.google.com>
- [x] My code follows the style guidelines of this project
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have verified my change on multiple browsers on different platforms
- [x] I have run `./build/all.py` and the build passes
- [x] I have run `./build/test.py` and all tests pass

### CODE REVIEW

File: lib/util/cmcd_manager.js [hunk 1]
```diff
@@ -131,7 +132,9 @@ shaka.util.CmcdManager = class {
         data.br = segmentInfo.bandwidth / 1000;
       }
 
-      data.tb = this.getTopBandwidth_(segmentInfo.type) / 1000;
+      if (isMedia && data.ot !== ObjectType.TIMED_TEXT) {
+        data.tb = this.getTopBandwidth_(data.ot) / 1000;
+      }
```
Comment (littlespex) [inline lib/util/cmcd_manager.js:137]: We can ignore top bitrate for text.

**Review by joeyparrish — APPROVED** [review]
