### PR TITLE
Fix index out of bound issue when parsing mp4 segment

### LINKED ISSUE #3402: MEDIA.BUFFER_READ_OUT_OF_BOUNDS when parsing segment in LL-Dash
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.1.0-master-15-g79d5fd8c (uncompiled)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chrome: 90.0.4430.93
macOS: 10.15.4 (19E287)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Sent to shaka-player-issues@google.com

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

`
{
  "streaming": {
    "lowLatencyMode": true
  }
}
`

**What did you do?**

Start video playback

**What did you expect to happen?**
No error

**What actually happened?**

Shaka Error MEDIA.BUFFER_READ_OUT_OF_BOUNDS observed

### PR DESCRIPTION
**Pull request by percytse**
## Description
Fixes #3402 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] I have signed the Google CLA <https://cla.developers.google.com>
- [x] My code follows the style guidelines of this project
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have verified my change on multiple browsers on different platforms
- [x] I have run `./build/all.py` and the build passes
- [x] I have run `./build/test.py` and all tests pass

### CODE REVIEW

File: lib/util/mp4_parser.js [hunk 1]
```diff
@@ -111,6 +111,12 @@ shaka.util.Mp4Parser = class {
   parseNext(absStart, reader, partialOkay, stopOnPartial) {
     const start = reader.getPosition();
 
+    // size(4 bytes) + type(4 bytes) = 8 bytes
+    if (start + 8 >= reader.getLength()) {
```
Comment (joeyparrish) [inline lib/util/mp4_parser.js:115]: Based on the parameter descriptions, I think this should depend on the stopOnPartial flag.  In some contexts, it should be an error to hit an incomplete box.  In LL-DASH context, I expect stopOnPartial should be true.  Is that correct?

**Review by joeyparrish — CHANGES_REQUESTED** [review]

**Comment by joeyparrish** [comment]
Thank you for contributing!

File: lib/util/mp4_parser.js (hunk 1 above)
Comment (percytse) [reply lib/util/mp4_parser.js:115]: Yes, you are correct. stopOnPartial is true in LL-Dash context.

File: lib/util/mp4_parser.js [hunk 2]
```diff
@@ -111,6 +111,12 @@ shaka.util.Mp4Parser = class {
   parseNext(absStart, reader, partialOkay, stopOnPartial) {
     const start = reader.getPosition();
 
+    // size(4 bytes) + type(4 bytes) = 8 bytes
+    if (stopOnPartial && start + 8 >= reader.getLength()) {
```
Comment (joeyparrish) [inline lib/util/mp4_parser.js:115]: I think == should be fine, right?  If a box had only the required size & name fields, `start + 8 == reader.getLength()` should be acceptable.  Do you agree?  Should this become `>` instead of `>=`?

Also, it looks like a similar check is needed below, when we handle `FULL_BOX` types and read `versionAndFlags`.

**Review by joeyparrish — CHANGES_REQUESTED** [review]

File: lib/util/mp4_parser.js (hunk 2 above)
Comment (percytse) [reply lib/util/mp4_parser.js:115]: Yes, I agree `start + 8 == reader.getLength()` should be acceptable.

**Review by joeyparrish — APPROVED** [review]
