### PR TITLE
fix: fix breaking captions

### LINKED ISSUE #3555: captions - captions break if the vvt loaded contains a cue that has a forward slash in its text
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
3.2.0

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
demo

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
chrome/macOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

load a VTT file that contains a cue that has a forward slash(/) in its text

**What did you expect to happen?**
caption track would load and cues would show up

**What actually happened?**

an exception is thrown and captions break entirely

### PR DESCRIPTION
**Pull request by bcupac**
## Description
Fixes #3555 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] I have signed the Google CLA <https://cla.developers.google.com>
- [x] My code follows the style guidelines of this project
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have verified my change on multiple browsers on different platforms
- [ ] I have run `./build/all.py` and the build passes
- [ ] I have run `./build/test.py` and all tests pass

### CODE REVIEW

File: lib/text/vtt_text_parser.js [hunk 1]
```diff
@@ -436,6 +435,9 @@ shaka.text.VttTextParser = class {
         }
         const tagEnd = payload.substring(i + 1, end);
         const tagStart = names.pop();
+        if (!tagEnd || !tagStart) {
+          return payload;
+        }
         if (tagStart === tagEnd) {
```
Comment (michellezhuogg) [inline lib/text/vtt_text_parser.js:441]: Shall we use `else if` here?

File: lib/text/vtt_text_parser.js [hunk 2]
```diff
@@ -341,7 +341,6 @@ shaka.text.VttTextParser = class {
 
     // Get the payload.
     const payload = text.slice(1).join('\n').trim();
-
```
Comment (michellezhuogg) [inline lib/text/vtt_text_parser.js:344]: Let's keep the empty line, to avoid possible merge conflicts.

**Review by michellezhuogg — COMMENTED** [review]
Thank you for fixing this!
