### PR TITLE
fix: avoid pts rollover correction for fmp4/cmaf streams

### LINKED ISSUE #10020: Avoid PTS rollover wrapping when playing HLS CMAF live streams
### FAQ

- [x] I have read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues

### If the problem is related to FairPlay, have you read the tutorial?

Not applicable

### What version of Shaka Player are you using?

5.1.0

### Can you reproduce the issue with our latest release version?

Yes

### Can you reproduce the issue with the latest code from `main`?

Yes

### Are you using the demo app or your own custom app?

Custom app

### What browser and OS are you using?

Safari / MacOS

### For embedded devices (smart TVs, etc.), what model and firmware version are you using?

_No response_

### What are the manifest and license server URIs?

Will provide over email if needed

### What configuration are you using? What is the output of `player.getNonDefaultConfiguration()`?

```
"{
  \"drm\": {
    \"retryParameters\": {
      \"maxAttempts\": 5,
      \"baseDelay\": 1200,
      \"fuzzFactor\": 0.4,
      \"timeout\": 40000,
      \"stallTimeout\": 18000,
      \"connectionTimeout\": 6000
    },
    \"servers\": {
      \"com.apple.fps\": \"https://lic.drmtoday.com/license-server-fairplay\"
    },
    \"advanced\": {
      \"com.apple.fps\": {
        \"distinctiveIdentifierRequired\": false,
        \"persistentStateRequired\": false,
        \"videoRobustness\": [],
        \"audioRobustness\": [],
        \"sessionType\": \"\",
        \"serverCertificateUri\": \"https://lic.drmtoday.com/license-server-fairplay/cert/tvm1\",
        \"individualizationServer\": \"\"
      }
    }
  },
  \"manifest\": {
    \"retryParameters\": {
      \"maxAttempts\": 5,
      \"baseDelay\": 1500,
      \"backoffFactor\": 2.2,
      \"fuzzFactor\": 0.4,
      \"timeout\": 40000,
      \"stallTimeout\": 18000,
      \"connectionTimeout\": 12000
    },
    \"defaultPresentationDelay\": 20,
    \"dash\": {
      \"clockSyncUri\": \"https://time.akamai.com/?iso\",
      \"ignoreMinBufferTime\": true
    }
  },
  \"streaming\": {
    \"retryParameters\": {
      \"maxAttempts\": 6,
      \"baseDelay\": 1500,
      \"backoffFactor\": 2.4,
      \"fuzzFactor\": 0.4,
      \"timeout\": 40000,
      \"stallTimeout\": 18000,
      \"connectionTimeout\": 12000
    },
    \"rebufferingGoal\": 6,
    \"bufferingGoal\": 60,
    \"ignoreTextStreamFailures\": true,
    \"useNativeHlsForFairPlay\": false
  },
  \"mediaSource\": {
    \"forceTransmux\": true
  },
  \"abr\": {
    \"defaultBandwidthEstimate\": 5000000,
    \"switchInterval\": 4,
    \"bandwidthUpgradeTarget\": 0.75,
    \"bandwidthDowngradeTarget\": 0.9
  },
  \"preferredAudio\": [
    {
      \"language\": \"sv\",
      \"role\": \"\",
      \"label\": \"\",
      \"channelCount\": 0,
      \"codec\": \"\"
    }
  ],
  \"preferredText\": [
    {
      \"language\": \"fi\",
      \"role\": \"\",
      \"format\": \"\"
    }
  ],
  \"preferredVideo\": [
    {
      \"label\": \"\",
      \"role\": \"\",
      \"codec\": \"\",
      \"hdrLevel\": \"AUTO\",
      \"layout\": \"\"
    }
  ],
  \"cmcd\": {
    \"sessionId\": \"50904542-8884-4c6f-bd13-454d943bb221\"
  }
}"
```

### What did you do?

Play a live stream with WebVTT subtitles that have a large timestamp, example:

WEBVTT
X-TIMESTAMP-MAP=LOCAL:00:00:00.000,MPEGTS:0

493568:48:11.610 --> 493568:48:14.730
Aletaan katsomaan,
mihin aika käytetään.

493568:48:14.849 --> 493568:48:19.051
Meillä on nytkin käytössä
uusia teknisiä sovelluksia, -

### What did you expect to happen?

Subtitles should be shown at the correct time

### What actually happened?

Subtitles are never shown.

I believe this is due to the PTS rollover calculations, if I disable that for HLS CMAF streams the subs will show up.

### Are you planning to send a PR to add it?

Yes

### PR DESCRIPTION
**Pull request by fredrik-telia**
For HLS CMAF streams with WebVTT subtitles with large timestamps, the rollover wrapping prevents the cues from being shown at the correct time.

By adding a check to only do the wrapping for MPEG-TS streams this problem is eliminated.

fixes #10020

### CODE REVIEW

**Comment by avelad** [comment]
Please, fix lint errors

**Comment by fredrik-telia** [comment]
> Please, fix lint errors

Absolutely, will do

File: AUTHORS [hunk 1]
```diff
@@ -126,4 +127,4 @@ Koen Romers <koenromers@gmail.com>
 Zhenghang Chen <czhtju@gmail.com>
 Xperi <*@xperi.com>
 Xiao Shen <dead.xx@gmail.com>
-Soumalya Bhattacharya <soumalyabhattacharya6@gmail.com>
\ No newline at end of file
+Soumalya Bhattacharya <soumalyabhattacharya6@gmail.com>
```
Comment (avelad) [inline AUTHORS]: Revert this change

File: CONTRIBUTORS [hunk 2]
```diff
@@ -178,4 +179,4 @@ Bidisha Das <officialbidisha1@gmail.com>
 Chafroud Tarek <chafroudtarek3@gmail.com>
 Xiao Shen <dead.xx@gmail.com>
 Emil Santurio <emil@qualabs.com>
-Soumalya Bhattacharya <soumalyabhattacharya6@gmail.com>
\ No newline at end of file
+Soumalya Bhattacharya <soumalyabhattacharya6@gmail.com>
```
Comment (avelad) [inline CONTRIBUTORS]: Revert this change

File: externs/shaka/text.js [hunk 3]
```diff
@@ -61,7 +61,8 @@ shaka.extern.TextParser = class {
  *   periodStart: number,
  *   segmentStart: number,
  *   segmentEnd: number,
- *   vttOffset: number
+ *   vttOffset: number,
+ *   isMpegTs: boolean
```
Comment (avelad) [inline externs/shaka/text.js]:
```suggestion
 *   isMpegTs: boolean,
```

File: externs/shaka/text.js [hunk 4]
```diff
@@ -73,7 +74,10 @@ shaka.extern.TextParser = class {
  * @property {number} vttOffset
  *     The start time relative to either segment or period start depending
  *     on <code>segmentRelativeVttTiming</code> configuration.
- *
```
Comment (avelad) [inline externs/shaka/text.js:76]: Re-add this line

**Review by avelad — COMMENTED** [review]
LGTM a few minor comments

File: externs/shaka/text.js [hunk 5]
```diff
@@ -74,6 +75,10 @@ shaka.extern.TextParser = class {
  *     The start time relative to either segment or period start depending
  *     on <code>segmentRelativeVttTiming</code> configuration.
  *
+ * @property {boolean} isMpegTs
+ *     True if the media container type is MPEG-TS (not fMP4)
+ *     needed to know if we should use rollover wrapping when
+ *     calculating offset for webvtt cues in hls streams
```
Comment (avelad) [inline externs/shaka/text.js]:
```suggestion
 * @property {boolean} isMpegTs
 *     True if the media container type is MPEG-TS (not fMP4)
 *     needed to know if we should use rollover wrapping when
 *     calculating offset for webvtt cues in hls streams
 *
```

**Review by avelad — APPROVED** [review]

**Comment by avelad** [comment]
A lot of tests are failing

**Comment by fredrik-telia** [comment]
> A lot of tests are failing

I'll see what I can do, might need some help figuring out what is going wrong

edit: should be sorted now, let me know if you want me to squash the commits
