### PR TITLE
Set server certificate before Store and Delete

### LINKED ISSUE #1623: Server certificate is not configured before Store and Delete operations
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**: v2.5.0-beta-master

**Can you reproduce the issue with our latest release version?**: yes

**Can you reproduce the issue with the latest code from `master`?**: yes

**Are you using the demo app or your own custom app?**: demo app

**If custom app, can you reproduce the issue using our demo app?**: yes

**What browser and OS are you using?**: Chrome/Windows 10

**What are the manifest and license server URIs?**:
Will send the manifest, license, and certificate URIs to shaka-player-issues@google.com

**What did you do?**
Added my asset to the demo assets list OR filled the manifest, license, and certificate URIs as Custom asset, select my asset and download it.

**What did you expect to happen?**
a) No errors in the debug console
b) The first (and only) license request raised from the CDM is for a license.

**What actually happened?**
a) The call to storage.configure raises an error:  "Invalid config, unrecognized key .progressCallback"

b) The first license request raised from the CDM is for a widevine certificate (2nd one is for a license)

### PR DESCRIPTION
**Pull request by gigon**
**Library**: Call setServerCertificate before store and delete operations, when serverCertificate exists:
In case of store(), it can be configured by the application.
In case of delete(), it is retrieved from the stored manifest.

**Demo application**: before store(), request and configure the certificate, when a certificateUri is given in asset.

Fixes #1623.

### CODE REVIEW

File: demo/offline_section.js [hunk 1]
```diff
@@ -202,11 +202,20 @@ shakaDemo.storeDeleteAsset_ = function() {
...
+
     let asset = shakaDemo.preparePlayer_(option.asset);
+
+    if (asset.certificateUri) {
+      configureCertificate = shakaDemo.requestCertificate_(asset.certificateUri)
+        .then(shakaDemo.configureCertificate_);
+    }
+
+    p = configureCertificate.then(function() {
     let nameField = document.getElementById('offlineName').value;
```
Comment (TheModMaker) [inline demo/offline_section.js]: This needs to be indented.  Running `./build/all.py` will check for style violations.

File: lib/media/drm_engine.js [hunk 2]
```diff
@@ -476,6 +462,40 @@ shaka.media.DrmEngine.prototype.attach = function(video) {
...
+ * Create a promise that will be resolved after the server certificate
+ * will be set.
+ *
+ * @return {!Promise|null}
+ */
+shaka.media.DrmEngine.prototype.setServerCertificate = function() {
+  goog.asserts.assert(this.initialized_,
+    'Must call init() before setServerCertificate');
+
+  let setServerCertificate = null;
```
Comment (TheModMaker) [inline lib/media/drm_engine.js]: If you set this to `Promise.resolve()`, you can have `@return {!Promise}`.

File: lib/media/drm_engine.js [hunk 3]
```diff
@@ -476,6 +462,40 @@ shaka.media.DrmEngine.prototype.attach = function(video) {
 };
 
 
+/**
+ * Create a promise that will be resolved after the server certificate
+ * will be set.
```
Comment (TheModMaker) [inline lib/media/drm_engine.js]: Suggestion:

> Sets the server certificate based on the current DrmInfo.

File: lib/offline/storage.js [hunk 4]
```diff
@@ -814,6 +814,7 @@ shaka.offline.Storage.prototype.createDrmEngine = async function(
   const config = this.config_;
   drmEngine.configure(config.drm);
   await drmEngine.initForStorage(variants, config.offline.usePersistentLicense);
+  drmEngine.setServerCertificate();
```
Comment (TheModMaker) [inline lib/offline/storage.js]: await

File: lib/offline/session_deleter.js [hunk 5]
```diff
@@ -70,13 +70,22 @@ shaka.offline.SessionDeleter = class {
...
+          bucket.info.serverCertificate,
           bucket.info.audioCapabilities, bucket.info.videoCapabilities);
     } catch (e) {
       shaka.log.warning('Error initializing EME', e);
       await drmEngine.destroy();
       return [];
     }
 
+    try {
+      drmEngine.setServerCertificate();
```
Comment (TheModMaker) [inline lib/offline/session_deleter.js]: await

File: lib/media/drm_engine.js [hunk 6]
```diff
@@ -476,6 +462,40 @@ shaka.media.DrmEngine.prototype.attach = function(video) {
...
+shaka.media.DrmEngine.prototype.setServerCertificate = function() {
+  goog.asserts.assert(this.initialized_,
+    'Must call init() before setServerCertificate');
+
+  let setServerCertificate = null;
+  if (this.mediaKeys_ &&
+      this.currentDrmInfo_ &&
+      this.currentDrmInfo_.serverCertificate &&
+      this.currentDrmInfo_.serverCertificate.length) {
+    setServerCertificate = this.mediaKeys_.setServerCertificate(
```
Comment (TheModMaker) [inline lib/media/drm_engine.js]: This would probably be easier to read as ES6 using `await` and `try`/`catch`.

File: demo/offline_section.js (hunk 1 above)
Comment (gigon) [reply demo/offline_section.js]: OK will fix.  
BTW I did run all.py (or check.py) and it does not trap this violation.

**Comment by gigon** [comment]
Thanks  @TheModMaker , I resolved the issues.

**Comment by joeyparrish** [comment]
Released in v2.5.0-beta2.
