### PR TITLE
Fix #3783 captions not working after a period transition on live DASH streams

### LINKED ISSUE #3783: Captions not working after a period transition on live DASH streams
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes i do not see a duplicate

**What version of Shaka Player are you using?**
3.1.2

**Can you reproduce the issue with our latest release version?**
I am certain the problem is present but I cannot reproduce because CEA 608 captions don't work at all because of this issue 
https://github.com/google/shaka-player/issues/3782

**Can you reproduce the issue with the latest code from `master`?**
No because CEA 608 captions are not working at all

**Are you using the demo app or your own custom app?**
Customer app

**If custom app, can you reproduce the issue using our demo app?**
No because CEA 608 captions are not working at all

**What browser and OS are you using?**
Chrome on Mac OS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
We will share stream information if necessary

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
We will share the configuration information if necessary

**What did you do?**
Play a multi-period live stream with CEA 608 captions embedded and that text track selected.

**What did you expect to happen?**
We expect to see captions in all periods that contain captions data.

**What actually happened?**
Captions disappear when we transition to a new period. 
Note that this problem does not occur with VOD streams

We have isolate the problem to this code in lib/text/text_engine.js storeAndAppendClosedCaptions()
```
if (id == this.selectedClosedCaptionId_) {
   this.displayer_.append([cue]);
}
```

At this point id is "CC1" and this.selectionCloseCaptionId_ is "CC1,,,," with the number of commas varying,

if we change this condition to this.selectedClosedCaptionId_.contains(id) captions work as expected.

### PR DESCRIPTION
**Pull request by caridley**
## Description
Fixes #3783

Embedded CEA-608 captions don't work on multi period live DASH DAI streams after new periods appear in the manifest because commas are appended the streams originalId string, which disrupts some stream matching code in text_engine.js

The problem has been resolved by preventing makeTextStreamsForClosedCaptions() from altering the PeriodCombiner.textStreams_ array.

## Screenshots (optional)
NA

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have signed the Google CLA <https://cla.developers.google.com>
- [x] My code follows the style guidelines of this project
- [NA] I have made corresponding changes to the documentation
- [No] I have added tests that prove my fix is effective or that my feature works
- [x] I have verified my change on multiple browsers on different platforms
- [x] I have run `./build/all.py` and the build passes
- [x] I have run `./build/test.py` and all tests pass

### CODE REVIEW

File: lib/text/text_engine.js [hunk 1]
```diff
@@ -396,7 +396,10 @@ shaka.text.TextEngine = class {
       }
 
       captionsMap.get(id).get(startAndEndTime).push(cue);
-      if (id == this.selectedClosedCaptionId_) {
+      // With multiperiod live DASH DAI streams a comma is appended to the
+      // selectedClosedCaptionId string each time a new period appears in
+      // the manifest e.g. "CC1,,," while the id value remains "CC1"
```
Comment (TheModMaker) [inline lib/text/text_engine.js:401]: That is either a bug in the caption parser or your content.  I don't think this should be handled here.

Comment (caridley) [reply lib/text/text_engine.js]: Ok found and fixed the root cause

**Review by joeyparrish — APPROVED** [review]
