### PR TITLE
fix: delay appending vtt subtitles depending on presence of discontinuity sequence and timestamp offset

### LINKED ISSUE #9470: VTT subtitles timing misalignment on HLS if the timestamp map doesn't account for discontinuity sequences
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

No

**What version of Shaka Player are you using?**

fork based on 4.10. I haven't tested latest main branch but the relevant piece of code seems mostly identical, so, I assume, it'll be an issue there too.

**Can you reproduce the issue with our latest release version?**

**Can you reproduce the issue with the latest code from `main`?**

**Are you using the demo app or your own custom app?**

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Safari, but likely any browser. Only have an example that runs on Safari at the moment.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

I don't have a stream to share.

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**

Standard config.

**What did you do?**

With HLS, we have an SSAI stream with segmented VTT captions in text file. It the VTT, the timestamp map, maps the VTT times to the content time.
content.vtt:
```vtt
WEBVTT
X-TIMESTAMP-MAP=MPEGTS:0,LOCAL:00:00:00.000

00:00:06.000 --> 00:00:08.000
example text
```
The HLS manifest looks something like this:
```m3u8
#EXT-X-DISCONTINUITY
#EXTINF:15,
empty.vtt
#EXT-X-DISCONTINUITY
#EXTINF:30,
content.vtt
```

**What did you expect to happen?**
I'd expect that the cue `example text` would display 6 seconds into its discontinuity sequence, or, 21s of the beginning of the combined timeline.

**What actually happened?**

Instead, depending on when the captions are enabled, the cues will show up at 6s rather than 21s. If I wait to make sure that the video segments from the second discontinuity sequence are loaded, then it will correctly display the cue at 21s.

This is because when VTT cues are parsed, it doesn't make sure that we have the correct timestamp offset associated with the particular discontinuity sequence. In here, https://github.com/shaka-project/shaka-player/blob/70904f52759af19b13e0f24b1f6a61be5878f7e5/lib/media/media_source_engine.js#L1149-L1159, the timestamp offset that we wait for could be from the first discontinuity, but we're already trying to parse `content.vtt`.

My proposal is that we should keep track of the timestamp offsets of each discontinuity sequence and if we're trying to parse the cues and we don't yet have the expected timestamp offset, we hold off until it is provided. Segment references already have a `discontinuitySequence` property on them, so, we can pass it in to the text engine. Then, [potentially here](https://github.com/shaka-project/shaka-player/blob/70904f52759af19b13e0f24b1f6a61be5878f7e5/lib/media/media_source_engine.js#L1254), we pass the timestamp offset along with the discontinuity sequence number to the text engine. When we call TextEngine#appendBuffer, we also pass the reference's discontinuitySequence through as well.

In TextEngine#appendBuffer, we can see if we have the correct timestamp offset and if so we can continue to parse, using that stored value. Otherwise, we'd want to delay parsing until we get the timestamp offset associated with that disco sequence. In playing around, I naively have it schedule a DelayedTick which just calls appendBuffer again, but there's probably a better way of handling that.

The TextEngine would also need a map of disco sequence numbers to timestamp offsets, rather than a single timestamp offset.

With my current naive implementation, seeking also produces `Assertion Failed: There should not be a gap in text references >1s` from the TextEngine, but I think that's addressable in the changes.

Any thoughts on the matter would also be greatly appreciated.

**Are you planning to send a PR to fix it?**
Yes. I'm working on changes on our fork but can submit a PR once that's ready/approved for contribution. But was also hoping for input on my proposal and the issue at hand.

### PR DESCRIPTION
**Pull request by gkatsev**
This PR changes the way that timestamp offsets are stored in the media source engine. Instead of a single value, it now has a map of values. For DASH, it should contain a single value, which is the last timestamp offset available. For HLS, it'll keep track of the timestamp offsets per discontinuity sequence. If content is appended and we don't yet have a timestamp offset for that discontinuity sequence number, it'll defer creating the cues until the timestamp offset is set, otherwise, the times for the cues may not be correct.

Fixes #9470

### CODE REVIEW

**Comment by gkatsev** [comment]
the PR build is failing because there's a leading space character but seems like I can't edit the PR title.

**Comment by avelad** [comment]
@shaka-bot test

**Comment by avelad** [comment]
It seems that fails in some platforms... can you review it? Thanks!

File: lib/text/text_engine.js [hunk 1]
```diff
@@ -250,6 +268,30 @@ shaka.text.TextEngine = class {
         return;
       }
     }
+
+    const removeInRange = (cue) => {
+      const inside = cue.startTime < endTime && cue.endTime > startTime;
+      return inside;
+    };
+
+    if (!this.deferredAppends_) {
```
Comment (matvp91) [inline lib/text/text_engine.js]: `deferredAppends_` seems always truthy, making this condition dead code?

Comment (gkatsev) [reply lib/text/text_engine.js]: Good catch! It must've stayed from an earlier version where it wasn't always set.

**Comment by gkatsev** [comment]
So, I think the test failures happen if the subtitles take a while to load and the second video segment ends up loading first, which changes the timestamp offset when they're parsed. During my testing previously, this is basically the same behavior as shaka had before this change.
At one point I experimented with not letting a timestamp offset get overridden once set but I think there were some scenarios that weren't correct.
A way to force this to happen for the one test is to add `|| this.timestampOffsetMap_.get(disco) != -1.4` to the `.has(disco)` in `appendBuffer`.

**Comment by avelad** [comment]
> So, I think the test failures happen if the subtitles take a while to load and the second video segment ends up loading first, which changes the timestamp offset when they're parsed. During my testing previously, this is basically the same behavior as shaka had before this change. At one point I experimented with not letting a timestamp offset get overridden once set but I think there were some scenarios that weren't correct. A way to force this to happen for the one test is to add `|| this.timestampOffsetMap_.get(disco) != -1.4` to the `.has(disco)` in `appendBuffer`.

That sounds like a hack with a magic number... I think the ideal solution is to find the root cause and fix it. Modifying the test to wait a certain amount of time is also a solution.

**Comment by gkatsev** [comment]
Oh, yeah, I didn't mean it was a solution but rather a way to reliably trigger the conditions for the test failure. I'll continue investigating this today.

**Comment by gkatsev** [comment]
ok, I think the root cause is the change in media source engine where previously the promise only got reset in `resync` which is only called in some cases, like when a disco sequence changes but now the timestamp offset always gets updated. I'll need to do some more testing on this.

**Comment by gkatsev** [comment]
It seems like having the timestamp offset only get set once per discontinuity makes the tests pass. Potentially, would need a way to unset it in the case of a resync call.
Going to continue looking into it and run some more tests on our streams to make sure that it doesn't cause other issues.

**Comment by gkatsev** [comment]
ok, I added a check for whether the timestamp offset should get updated or not. In my testing it seems to be working fine for both multiperiod DASH and HLS content with discontinuities.

One thing to thing I noticed is that in DASH, when seeking back across a period, shaka inserts the init segment from the period we seeked away from resulting in the captions being offset. It doesn't always happen but it isn't hard to reproduce. This PR doesn't address that issue. While it may be possible to work around it on the text engine/MSE side, it might be nice to figure out why the incorrect init segments gets appended.

File: lib/text/text_engine.js [hunk 2]
```diff
@@ -21,22 +22,32 @@ goog.require('shaka.util.MimeUtils');
  * @export
  */
 shaka.text.TextEngine = class {
-  /** @param {shaka.extern.TextDisplayer} displayer */
-  constructor(displayer) {
+  /**
+   * @param {shaka.extern.TextDisplayer} displayer
+   * @param {string=} manifestType
+   */
+  constructor(displayer, manifestType = shaka.media.ManifestParser.DASH) {
```
Comment (gkatsev) [inline lib/text/text_engine.js]: now that the manifest type is passed here, we technically don't need to pass it in `initParser` below. I didn't make that change yet, but happy to do so.

Comment (avelad) [reply lib/text/text_engine.js]: Please do it ! Thanks!

**Comment by avelad** [comment]
@shaka-bot test

**Comment by gkatsev** [comment]
looks like there's stil more work for me https://github.com/shaka-project/shaka-player/actions/runs/22002953987/job/63583998586?pr=9676#step:13:365 😭

**Comment by gkatsev** [comment]
running the test locally in safari via karma's debug page seems to pass. It's off by exactly the first timestamp offset still.

**Comment by gkatsev** [comment]
I can reproduce when running karma on safari directly, so, I guess I'll take another look at it next week.

File: lib/text/text_engine.js [hunk 3]
```diff
@@ -21,22 +22,32 @@ goog.require('shaka.util.MimeUtils');
...
 
     /** @private {boolean} */
     this.external_ = false;
 
-    /** @private {number} */
-    this.timestampOffset_ = 0;
+    /** @private {Map<number, number>} */
+    this.timestampOffsetMap_ = new Map();
+    // default timestamp offset for no discontinuities to 0
+    this.timestampOffsetMap_.set(-1, 0);
```
Comment (gkatsev) [inline lib/text/text_engine.js]: i think the root cause of the new failure is this change. While it seems to work for the most part, it means that there's a chance that we get text segments appended before a proper timestamp offset is set from the media source engine. It was initially added because a bunch of tests were failing and that worked around it. Instead, probably need to remove it and fixup the tests.

**Comment by gkatsev** [comment]
I think this is good to go again.

**Comment by avelad** [comment]
@shaka-bot test

File: lib/text/text_engine.js [hunk 4]
```diff
@@ -11,6 +11,7 @@ goog.require('shaka.media.ClosedCaptionParser');
 goog.require('shaka.text.Cue');
 goog.require('shaka.util.BufferUtils');
 goog.require('shaka.util.IDestroyable');
+goog.require('shaka.media.ManifestParser');
```
Comment (avelad) [inline lib/text/text_engine.js]: sort alphabetically

File: lib/text/text_engine.js [hunk 5]
```diff
@@ -21,22 +22,30 @@ goog.require('shaka.util.MimeUtils');
...
     /** @private {boolean} */
     this.segmentRelativeVttTiming_ = false;
 
     /** @private {boolean} */
     this.external_ = false;
 
-    /** @private {number} */
-    this.timestampOffset_ = 0;
+    /** @private {Map<number, number>} */
+    this.timestampOffsetMap_ = new Map();
```
Comment (avelad) [inline lib/text/text_engine.js:46]: Add a blank line between these properties

File: lib/text/text_engine.js [hunk 6]
```diff
@@ -166,12 +176,23 @@ shaka.text.TextEngine = class {
...
 
+    // if we're trying to append content associated with a particular
+    // discontinuity sequence delay that append until after we have received
+    // its associated timestamp offset
+    if (!this.timestampOffsetMap_.has(disco)) {
+      const deferredAppends = this.deferredAppends_.get(disco) || [];
+      deferredAppends.push({buffer, startTime, endTime, uri, disco});
+      this.deferredAppends_.set(disco, deferredAppends);
+      return;
+    }
```
Comment (avelad) [inline lib/text/text_engine.js:197]: This is only true `if !(this.segmentRelativeVttTiming_ || this.external_)`

**Review by avelad — CHANGES_REQUESTED** [review]
LGTM, only a few minor comments

File: lib/text/text_engine.js (hunk 6 above)
Comment (gkatsev) [reply lib/text/text_engine.js:197]: you're saying that we shouldn't defer appends in the case that segment relative vtt timing or external is set?

Comment (avelad) [reply lib/text/text_engine.js:197]: If it's external, it shouldn't have any discontinuities, so there's no need to wait, right?

Comment (gkatsev) [reply lib/text/text_engine.js:197]: yeah, potentially. Though, at the moment, the text engine doesn't have a default timestamp offset. But I'll take a look at what making this change.

Comment (gkatsev) [reply lib/text/text_engine.js:197]: made the change but only for external. It seems like for hls, even with `segmentRelativeVttTiming_` it reads `time.periodStart` which otherwise would end up being unset.

**Comment by avelad** [comment]
@shaka-bot test

**Review by avelad — APPROVED** [review]
