### PR TITLE
Catch BAD_HTTP_STATUS error thrown by makeResponse in xhr.onload

### LINKED ISSUE #1302: Uncaught BAD_HTTP_STATUS error in xhr.onload
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
Yes

**What version of Shaka Player are you using?**:
Latest from master

**Can you reproduce the issue with our latest release version?**:
Did not test

**Can you reproduce the issue with the latest code from `master`?**:
Yes

**Are you using the demo app or your own custom app?**:
Demo app

**What browser and OS are you using?**:
Chrome 63 macOS

**What are the manifest and license server URIs?**:
Any demo content should do

**What did you do?**
Rewrite manifest response to HTTP error status

**What did you expect to happen?**
No uncaught errors

**What actually happened?**
Chrome logs an uncaught error.
screen shot 2018-02-13 at 2 26 42 pm

The failure is obscured by the fact that the sample app listens for `error` events from `window`. Unit tests aren't failing because promise-polyfill (used by promise-mock, per test/util/boot.js) catches otherwise uncaught exceptions and rejects the Promise in the test.

### PR DESCRIPTION
**Pull request by chrisfillmore**
Also wrap mock XHR event handlers in try-catch blocks in
http_plugin_unit to avoid regression.

Resolves #1302

### CODE REVIEW

File: lib/net/http_xhr_plugin.js [hunk 1]
```diff
@@ -62,10 +62,15 @@ shaka.net.HttpXHRPlugin = function(uri, request, requestType) {
             return all;
           },
           {});
-      var response = shaka.net.HttpPluginUtils.makeResponse(headers,
-          target.response, target.status, uri, target.responseURL,
-          requestType);
-      resolve(response);
+
+      try {
+        var response = shaka.net.HttpPluginUtils.makeResponse(headers,
```
[the remark this answers is not in the document]
Comment (joeyparrish) [reply lib/net/http_xhr_plugin.js]: In fact, we landed that change today.  :-)

File: lib/net/http_xhr_plugin.js [hunk 2]
```diff
@@ -62,10 +62,15 @@ shaka.net.HttpXHRPlugin = function(uri, request, requestType) {
...
+            target.response, target.status, uri, target.responseURL,
+            requestType);
+        resolve(response);
+      } catch (error) {
+        reject(error);
```
Comment (joeyparrish) [inline lib/net/http_xhr_plugin.js]: If error is something other than shaka.util.Error, you'll want to wrap this.

Comment (theodab) [reply lib/net/http_xhr_plugin.js]: I don't know if this could be anything but a shaka.util.Error. This is catching thrown errors from makeResponse, which only throws an error in one place, and that's a shaka.util.Error. Nothing else in that function is something that could throw by itself, I don't think.

Comment (joeyparrish) [reply lib/net/http_xhr_plugin.js]: Okay, fair enough.

Comment (chrisfillmore) [reply lib/net/http_xhr_plugin.js]: I actually agree with @joeyparrish, there should not be unchecked errors, so I added an assertion.

**Comment by chrisfillmore** [comment]
I've rebased but I see what @theodab pointed out, we still have an uncaught error in the promise chain in NetworkingEngine. Investigating...

**Comment by chrisfillmore** [comment]
@theodab I've filed #1323 for the uncaught error in the Promise. I believe that is a separate issue than the one resolved in this PR.
