### PR TITLE
fix(UI): Make Overflow/Settings Menu position dynamic

### LINKED ISSUE #9287: Overlay Menu does not follow overlay button position
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the question is related to FairPlay, have you read the tutorial?**

It is not related to fairplay

**What version of Shaka Player are you using?**
4.16.6

**What browser and OS are you using?**
1. Chrome, Ubuntu 24.04.
2. Chrome Android 15.

**Please ask your question**
I configured overlay button, but the problem is overlay menu is not following the overlay button. The menu is stuck to right only. I want to know what can I do to fix it
See this screenshot for more clarity:

Image

### PR DESCRIPTION
**Pull request by opticSquid**
Close #9287

### CODE REVIEW

File: ui/overflow_menu.js [hunk 1]
```diff
@@ -106,7 +106,7 @@ shaka.ui.OverflowMenu = class extends shaka.ui.Element {
     /** @private {ResizeObserver} */
     this.resizeObserver_ = null;
 
-    const resize = () => this.computeMaxHeight_();
+  const resize = () => this.computeOverFlowMenuPos_();
```
Comment (matvp91) [inline ui/overflow_menu.js]: Wrong indention, the linter is going to complain.

File: ui/overflow_menu.js [hunk 2]
```diff
@@ -216,7 +216,8 @@ shaka.ui.OverflowMenu = class extends shaka.ui.Element {
           Iterables.filter(this.overflowMenu_.childNodes, isDisplayed);
         /** @type {!HTMLElement} */ (visibleElements[0]).focus();
       }
-      this.computeMaxHeight_();
+      this.computeOverFlowMenuPos_();
+      this.computeOverFlowMenuPos_();
```
Comment (matvp91) [inline ui/overflow_menu.js]: You're calling this twice.

File: ui/overflow_menu.js [hunk 3]
```diff
@@ -230,11 +231,11 @@ shaka.ui.OverflowMenu = class extends shaka.ui.Element {
         this.localization.resolve(LocIds.MORE_SETTINGS);
   }
 
-
```
Comment (matvp91) [inline ui/overflow_menu.js:228]: Revert this line.

File: ui/overflow_menu.js [hunk 4]
```diff
@@ -230,11 +231,11 @@ shaka.ui.OverflowMenu = class extends shaka.ui.Element {
...
   /**
    * @private
    */
-  computeMaxHeight_() {
+  computeOverFlowMenuPos_() {
```
Comment (matvp91) [inline ui/overflow_menu.js]: I'd recommend renaming this. Using the term `OverflowMenu` in the function name is redundant given that the component itself is already named OverflowMenu.

What about `computeMaxHeightAndPosition_`?

File: ui/overflow_menu.js [hunk 5]
```diff
@@ -244,6 +245,32 @@ shaka.ui.OverflowMenu = class extends shaka.ui.Element {
...
+    // Compute horizontal position
+    const bottomControlsPos = this.controlsContainer_.getBoundingClientRect();
+    const overflowMenuButtonPos =
+        this.overflowMenuButton_.getBoundingClientRect();
+    const leftGap = overflowMenuButtonPos.left - bottomControlsPos.left;
+    const rightGap = bottomControlsPos.right - overflowMenuButtonPos.right;
+
+    // Overflow menu button is either placed to the left or center
+    if (leftGap < rightGap) {
+      let overflowMenuLeftEdge = leftGap - 15;
```
Comment (matvp91) [inline ui/overflow_menu.js]: I'd make `15` a constant, eg; `EDGE_PADDING`.

File: ui/overflow_menu.js [hunk 6]
```diff
@@ -244,6 +245,32 @@ shaka.ui.OverflowMenu = class extends shaka.ui.Element {
...
+      // if the overflow menu's left edge is less than 15px
+      // from the left edge of the video container
+      if (overflowMenuLeftEdge - bottomControlsPos.left < 15) {
```
Comment (matvp91) [inline ui/overflow_menu.js]:
```js
let left = leftGap - EDGE_PADDING;
// We can one line this for clarity.
left = Math.max(left, EDGE_PADDING);
```

**Review by matvp91 — CHANGES_REQUESTED** [review]

**Comment by matvp91** [comment]
Hi @opticSquid, thank you for the PR.

I added a few comments, and there's an error thrown by the linter: https://github.com/shaka-project/shaka-player/actions/runs/19402973584/job/55535748531?pr=9395

File: ui/overflow_menu.js (hunk 1 above)
Comment (opticSquid) [reply ui/overflow_menu.js]: yes I spotted it now. How can I run the linter locally so that I can fix the issues before commit and push

**Comment by opticSquid** [comment]
I have fixed the formatting errors and renamed the function for now. Give me some time I will fix the logic as well

File: ui/overflow_menu.js [hunk 7]
```diff
@@ -265,4 +292,3 @@ shaka.ui.Controls.registerElement(
 
 /** @private {!Map<string, !shaka.extern.IUIElement.Factory>} */
 shaka.ui.OverflowMenu.elementNamesToFactories_ = new Map();
-
```
Comment (avelad) [inline ui/overflow_menu.js:263]: Please revert this line

File: ui/overflow_menu.js (hunk 3 above)
Comment (opticSquid) [reply ui/overflow_menu.js:228]: done

**Comment by opticSquid** [comment]
I have addressed all the reviews in the PR. Please let me know if there is some additonal feedback

File: ui/overflow_menu.js (hunk 3 above)
Comment (opticSquid) [reply ui/overflow_menu.js:228]: I don't know I don't even see this extra line in my code. how to revert it

File: ui/overflow_menu.js
Comment (opticSquid) [inline ui/overflow_menu.js:228]: @avelad now its 2 lines only which is standard

File: ui/overflow_menu.js (hunk 2 above)
Comment (opticSquid) [reply ui/overflow_menu.js]: done

File: ui/overflow_menu.js (hunk 4 above)
Comment (opticSquid) [reply ui/overflow_menu.js]: renamed it

File: ui/overflow_menu.js (hunk 6 above)
Comment (opticSquid) [reply ui/overflow_menu.js]: done

File: ui/overflow_menu.js (hunk 7 above)
Comment (opticSquid) [reply ui/overflow_menu.js:263]: done

**Comment by matvp91** [comment]
Thank you, code looks good to me.

I'll wait for @avelad to approve this too.

**Comment by opticSquid** [comment]
Sure thanks a lot.

**Comment by opticSquid** [comment]
I am trying to fix settings menu too. But I don't know how can I detect overflow menu button position from settings menu so that I can place the menu correctly. Do you have any idea in mind?

**Comment by avelad** [comment]
> I am trying to fix settings menu too. But I don't know how can I detect overflow menu button position from settings menu so that I can place the menu correctly. Do you have any idea in mind?

@joeyparrish any idea?

**Comment by opticSquid** [comment]
> I'm not convinced about the change, because it's only half-finished. And besides, the menus in the demo don't behave correctly.
> 
> https://github.com/user-attachments/assets/87bfec09-8c34-4bc6-b5fc-a33b063f5c8d

It seems to me it occurs because settings menu also needs changes which is not applied yet. I have only made changes in the first menu that appears i.e., overflow menu

**Comment by joeyparrish** [comment]
I'm not sure this is the right approach.  I think we might want something based in the layout.  Instead of adjusting the position of each menu to match the button, we should perhaps have a single hierarchy in the DOM that contains all such menus, and position that.

**Comment by opticSquid** [comment]
Hey.. sorry I was absent here due to my work pressure. Will resume from tomorrow. I saw the plan the release v5 before Christmas. I will try to finish this off this weekend only

**Comment by opticSquid** [comment]
> I'm not sure this is the right approach. I think we might want something based in the layout. Instead of adjusting the position of each menu to match the button, we should perhaps have a single hierarchy in the DOM that contains all such menus, and position that.

Can you explain a little bit more..

**Comment by avelad** [comment]
I'm working on refactoring all the menus to make it easier to have and detect submenus. Once that's finished, we can return to this pull request.

**Comment by opticSquid** [comment]
> I'm working on refactoring all the menus to make it easier to have and detect submenus. Once that's finished, we can return to this pull request.

Ok

**Comment by avelad** [comment]
@opticSquid I created https://github.com/shaka-project/shaka-player/pull/9485 to simplify the sub menus. This PR enables yours to function correctly, although you would have to make the same change in shaka.ui.SettingsMenu

**Comment by opticSquid** [comment]
> @opticSquid I created https://github.com/shaka-project/shaka-player/pull/9485 to simplify the sub menus. This PR enables yours to function correctly, although you would have to make the same change in shaka.ui.SettingsMenu

Ok. I will see the PR and go ahead

**Comment by avelad** [comment]
> > @opticSquid I created #9485 to simplify the sub menus. This PR enables yours to function correctly, although you would have to make the same change in shaka.ui.SettingsMenu
> 
> Ok. I will see the PR and go ahead

Merged!, can you rebase and re-do your changes? Thanks!

**Comment by opticSquid** [comment]
> > > @opticSquid I created #9485 to simplify the sub menus. This PR enables yours to function correctly, although you would have to make the same change in shaka.ui.SettingsMenu
> > 
> > Ok. I will see the PR and go ahead
> 
> Merged!, can you rebase and re-do your changes? Thanks!

Ok

**Comment by avelad** [comment]
@opticSquid I updated your PR with the changes, can you review it?

**Comment by avelad** [comment]
@absidue FYI!

**Comment by opticSquid** [comment]
Hey I'm in hospital right now due to a surgery scheduled tonight. Currently viewing this through mobile. Allow me some time till sunday. I will return home on sunday and try to review it

**Comment by opticSquid** [comment]
I tested it. Looks Perfect to me. In my opinion we are good to merge it
