### PR TITLE
Thumbnail position calculation

### LINKED ISSUE #3511: player.getThumbnails incorrectly calculates the Y position
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.1.1 and master branch 3.2.0-pre

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome + mac OS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
Tested against 
- https://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel-tiled-thumbnails-timeline.ism/.mpd
- https://dash.akamaized.net/akamai/bbb_30fps/bbb_with_multiple_tiled_thumbnails.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Not relevant

**What did you do?**
I've been experimenting with implementing a custom UI that would display the correct thumbnail when scrubbing the seekbar. 
The current logic incorrectly calculates the Y position of the thumbnail in the thumbnail sheet resulting in the incorrect thumbnails being displayed when calling `player.getThumbnails` with the current time.

**What did you expect to happen?**
The correct thumbnail to be displayed for the supplied time.

**What actually happened?**
The `positionY` aka `row` position gets calculated incorrectly. Current implementation uses the following calculation:
```
positionY = (thumbnailPosition % rows) / rows * fullImageHeight;
 ```
 
 For a 4x4 grid of 200X100px
 ```
 [0][1]
 [2][3]
 ```
 
 When calculating the position for thumbnail 1 the position returned would be:
 ```
 positionX = 100;
 positionY = 50;
 ```
 instead of the correct position:
  ```
 positionX = 100;
 positionY = 0;
 ```

I have a PR ready that addresses this bug.

### PR DESCRIPTION
**Pull request by paulJordaan**
## Description
 Fix Y position calculation for the `getThumbnails` funtion.
 Fixes #3511 
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] I have signed the Google CLA <https://cla.developers.google.com>
- [x] My code follows the style guidelines of this project
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have verified my change on multiple browsers on different platforms
- [x] I have run `./build/all.py` and the build passes
- [x] I have run `./build/test.py` and all tests pass

### CODE REVIEW

File: lib/player.js [hunk 1]
```diff
@@ -3422,8 +3422,8 @@ shaka.Player = class extends shaka.util.FakeEventTarget {
         const segmentTime = reference.endTime - reference.startTime;
         const thumbnailPosition =
             Math.floor(thumbnailTime * totalImages / segmentTime);
-        positionX = (thumbnailPosition % columns) / columns * fullImageWidth;
-        positionY = (thumbnailPosition % rows) / rows * fullImageHeight;
+        positionX = (thumbnailPosition % columns) * width;
+        positionY = Math.floor(thumbnailPosition / columns) * height;
```
Comment (avelad) [inline lib/player.js:3426]: Should be: `Math.floor(thumbnailPosition / rows) * height;`

(columns vs rows)

Comment (paulJordaan) [reply lib/player.js:3426]: @avelad I've checked the logic again and the use of columns is correct. Consider the following as per the unit test.
Grid of 2x3 100x150px:
```
[0][1]
[2][3]
[4][5]
```

Requesting the position of thumbnail 5 using your suggested edit would result in the following:
```
Math.floor(thumbnailPosition / rows) * height
Math.floor( 5 / 3) * 50
1 * 50
yPosition = 50
```

The correct position for thumbnail 5 should be:
```
x= 50
y= 100
```

**Review by joeyparrish — APPROVED** [review]
