### PR TITLE
fix: Avoid uncaught TypeError when destroying player during DRM key status change

### LINKED ISSUE #9983: Race condition in player.destroy(): onKeyStatus_ accesses null streamingEngine_
### FAQ
- [x] I have read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues

### If the problem is related to FairPlay, have you read the tutorial?
Not applicable

### What version of Shaka Player are you using?
v4.16.10

### Can you reproduce the issue with our latest release version?
Yes (confirmed same code path in v4.16.27)

### Can you reproduce the issue with the latest code from `main`?
Yes (confirmed same code path in v5.1.0)

### Are you using the demo app or your own custom app?
Custom app

### What browser and OS are you using?
- Samsung Tizen 6.0–9.0 (Safari/WebKit)
- Hisense VIDAA (Chrome 111)
- LG webOS TV 25 (Chrome 120)
- Also reproducible on Chrome desktop with CPU 6x throttle

### For embedded devices (smart TVs, etc.), what model and firmware version are you using?
Samsung Smart TVs (Tizen 6.0–9.0), Hisense Smart TVs (Chrome 111), LG Smart TVs (webOS TV 25 / Chrome 120)

### What are the manifest and license server URIs?
Any DRM-protected DASH content (Widevine or PlayReady). Not specific to a manifest — the bug is in the player teardown sequence.

### What configuration are you using?
Not configuration-dependent. Reproducible with default DRM config.

### What did you do?
1. Load DRM-protected DASH content via `player.load()` (Widevine on Chrome/Tizen/Hisense, PlayReady on LG webOS)
2. While content is actively streaming, call `player.destroy()`
3. Repeat — it's a race condition, more frequent on slower CPUs (use Chrome DevTools CPU 6x throttle to reproduce on desktop)

### What did you expect to happen?
`player.destroy()` completes without errors.

### What actually happened?

`TypeError: Cannot read properties of null` thrown from `onKeyStatus_()` accessing `this.streamingEngine_.getCurrentVariant()` after `streamingEngine_` has already been set to null.

**Stack trace:**
```
streaming_engine.js:391 Uncaught TypeError: Cannot read properties of null (reading 'o')
    or @ streaming_engine.js:391         ← getCurrentVariant()
    (anonymous) @ player.js:2419         ← this.onKeyStatus_(map)
    qo @ preload_manager.js:177          ← queued callback
    onKeyStatus @ player.js:2417         ← drmPlayerInterface.onKeyStatus
    Hh @ drm_engine.js:1741             ← processKeyStatusChanges_()
    (anonymous) @ drm_engine.js:118      ← keyStatusTimer_
    (anonymous) @ timer.js:65            ← tick
    (anonymous) @ delayed_tick.js:56     ← setTimeout
```

**Root cause:**

`player.destroy()` calls `destroyStreaming_()` and `destroyDrmEngine_()` in parallel via `Promise.all()`. This creates a race:

1. `destroyStreaming_()` sets `this.streamingEngine_ = null`
2. Meanwhile, closing the DRM session causes the CDM to fire `keystatuseschange`
3. `DrmEngine.onKeyStatusChange_` batches it via `keyStatusTimer_.tickAfter(KEY_STATUS_BATCH_TIME)`
4. The `setTimeout` fires after `streamingEngine_` is already null
5. `processKeyStatusChanges_()` → `playerInterface_.onKeyStatus()` → `onKeyStatus_()` accesses `this.streamingEngine_.getCurrentVariant()` on null

`DrmEngine.destroyNow_()` does call `keyStatusTimer_.stop()` (line 180), but if the timer callback has already been picked up by the event loop, `stop()` is too late.

The `goog.asserts.assert(this.streamingEngine_)` at the top of `onKeyStatus_` is stripped in production builds, leaving no runtime guard.

**Suggested fix:**

Add a null guard in `onKeyStatus_`:

```js
onKeyStatus_(keyStatusMap) {
    if (!this.streamingEngine_) return;
    // ... rest of method
}
```

**Impact:** ~13,000 events affecting ~10,000 users over 90 days on our Smart TV app. Slow TV CPUs widen the race window significantly compared to desktop/mobile.

### Are you planning to send a PR to add it?
Yes

### PR DESCRIPTION
**Pull request by karimlaham**
Fixes #9983

## Summary

`player.destroy()` can race with a pending `keystatuseschange` callback, causing a `TypeError: Cannot read properties of null` when `onKeyStatus_()` accesses `this.streamingEngine_` after it has been nulled by `destroyStreaming_()`.

This adds a null guard at the top of `onKeyStatus_()` to bail out early if the streaming engine has already been torn down.

## Root cause

`destroyStreaming_()` and `destroyDrmEngine_()` run in parallel via `Promise.all()`. Closing the DRM session triggers `keystatuseschange` from the CDM, which is batched via `keyStatusTimer_.tickAfter()`. If the `setTimeout` callback fires after `streamingEngine_` is set to null but before `DrmEngine.destroyNow_()` calls `keyStatusTimer_.stop()`, the stale callback crashes.

The existing `goog.asserts.assert` is stripped in production builds, so there is no runtime protection.

## Impact

~13,000 error events affecting ~10,000 users over 90 days on Smart TV apps (Samsung Tizen, Hisense VIDAA, LG webOS). Slow TV CPUs widen the race window significantly.

## Test plan

- [x] Verified fix on Samsung Tizen 6.0–9.0, Hisense VIDAA (Chrome 111), LG webOS TV 25 (Chrome 120)
- [x] Reproducible on Chrome desktop with CPU 6× throttle — confirmed fix eliminates the crash
- [x] No behavioral change when `streamingEngine_` is non-null (normal path unchanged)

Co-Authored-By: Claude (Opus 4.6) <noreply@anthropic.com>

### CODE REVIEW

**Comment by matvp91** [comment]
How exactly do you run into this?
Calling destroy immediately after a load promise resolve, do you rely on key rotation?

I'm surprised we didn't bump into this ourselves.

File: lib/player.js [hunk 1]
```diff
@@ -8949,6 +8949,9 @@ shaka.Player = class extends shaka.util.FakeEventTarget {
    * @private
    */
   onKeyStatus_(keyStatusMap) {
+    if (!this.streamingEngine_) {
+      return;
+    }
     goog.asserts.assert(this.streamingEngine_, 'Cannot be called in src= mode');
```
Comment (matvp91) [inline lib/player.js]: The assert would be meaningless if we bail out early.

**Review by matvp91 — CHANGES_REQUESTED** [review]

**Comment by karimlaham** [comment]
Not key rotation, just the normal `keystatuseschange` from the CDM racing with `player.destroy()` when the user navigates away from playback. We see it mostly on Smart TV hardware (~13k events, ~10k users over 90 days). Also managed to reproduce it occasionally on Chrome with 20× CPU throttle, and can consistently reproduce it on the mentioned TVs.

File: lib/player.js (hunk 1 above)
Comment (karimlaham) [reply lib/player.js]: Good catch, I'll remove it.

**Review by avelad — APPROVED** [review]

**Review by matvp91 — APPROVED** [review]
